import subprocess

closes = {
339: """Fixed in PR #377 (`fix/native-storyboard-refresh` 478b3c6 + lead gate fixes): OnCanvasKey is now attached to the page canvas element (the WorkflowView pattern) with a second TextBoxBase/ComboBox focus guard, covering Backspace/Delete, arrows and Tab; canvas selection paths focus the canvas so shortcuts stay available. Verified by the new InspectorKeyIsolationChecks (raises real tunnel-routed PreviewKeyDown with focus inside the dialogue TextBox — five assertion groups) and the full `--render` chain: 54 checks green on the Windows real machine, plus `npm run check` exit 0.""",
341: """Fixed in PR #377 (`fix/native-storyboard-refresh` 1345b5d): StoryboardView.RefreshAsync now refetches server anchors with preserveDrafts:true (web refetch semantics — geometry drafts, undo stack and dialogue drafts survive); ScriptView.RefreshAsync early-returns while editing forms are open. Verified by RefreshKeepsDraftsChecks + ScriptRefreshKeepsFormsChecks in the `--render` chain (54 green) on the integrated tree.""",
345: """Fixed in PR #377 (`fix/desktop-scripts-hardening` 221f1ef): README desktop section now states plan-B is implemented and e2e-verified (17 tests, counts cross-checked per parametrize), maps all 14 scripts, corrects the migration count to 31 (counted on disk), and describes the sidecar's full plan-B lifecycle duties. Verified by a 10-point Select-String sweep against the shipped code. (The D7 row's separate historical 28-migration reference is tracked in #372.)""",
346: """The two named defects (readiness-timeout helper kill, AbortSignal on the health probe) had already landed in b521675/#336-series before this issue was filed; PR #377 (`fix/desktop-scripts-hardening` 6c8b512) closed the REMAINING leak paths — every throw after spawn that bypasses fail() (malformed READY JSON, unreadable journal, browser-phase exceptions) now reaches a module-scope helper handle and best-effort group-kills in main().catch. Probe verified by an independent kill-path harness (error → kill attempt → ESRCH swallowed → exit 1).""",
347: """Fixed in PR #377 (`fix/desktop-scripts-hardening` 390e4af): assembly now stages into a same-volume web.tmp-<pid> tree, moves the old tree aside, rename-swaps, and deletes the old tree only after success — with rollback if the final rename fails. A monkeypatched copytree failure mid-run proves the previous tree stays byte-identical (2/2 tests, tests/test_assemble_web_resources.py).""",
348: """Fixed in PR #377 (`fix/desktop-scripts-hardening` ec6ee04): timeout path tree-kills via taskkill /T /F (Stop-SampleTree), the finally block belt-kills a still-running sample (Ctrl+C/mid-sample throw no longer leak the native-host→sidecar tree holding its port), and the dead USER_DATA pre-assignment is gone. Demonstrated with a real process tree: old code leaked children 5s+; new kill eliminates the tree including conhost within 250ms.""",
300: """Plan-B/web half fixed in PR #377 (`fix/csp-unsafe-inline` 2abd7a5 + 36ea923): the CSP ships as a per-request nonce policy (apps/web/proxy.ts + lib/csp.ts, dynamic rendering via layout.tsx `connection()`), script-src drops both 'unsafe-inline' and 'wasm-unsafe-eval'; pinned twice (next-config-csp.test.ts + shell-core delivery_contract.rs plan_b test, 9/9). End-to-end evidence: next start + real-browser zero CSP violations, 16/16 scripts nonce-carrying, standalone server.js form identical; vitest 464/464; production build green. Also allows the .env.example-documented localhost API spelling (review finding). The static-export form's unsafe-inline remainder is now separately tracked in #378 with the feasibility evidence — closing this umbrella.""",
307: """Closed by lead decision (option 3 — accept and document as a same-user residual), recorded with rationale in output/n3-desktop-threat-model.md (ported to master in PR #377): the prerequisite is a same-user process with netstat-level discovery; the announced port has been helper-owned and Windows-exclusive since #301, leaving only node's internal ephemeral port; the loopback trust model already treats same-user as inside the boundary; the identity-challenge option only detects non-proxying co-binds and a helper-owned HTTP front is an architecture change not justified by a P3 same-user residual. Reopen if the threat model ever brings same-user inside the boundary.""",
311: """Closed by lead decision, recorded in output/n3-desktop-threat-model.md (PR #377): part 1 (junction guard) is VERIFIED — the first-ever Windows-leg run of the in-root junction pin in `sweep_never_removes_through_planted_links` PASSES (current toolchain reports junction reparse points as is_dir()==false, so guard 1 excludes them; no production change needed); part 2 (created/ready crash residue) is a deliberate no-auto-reclaim policy — a wrong reclaim would delete a live session's ownership journal (the WPF leg shares the layout without a single-instance mutex), and the skip-non-terminal behavior is asserted by tests. Reopen condition: a cross-platform pid+starttime liveness oracle with a lead-reviewed safety argument.""",
}

for number, body in closes.items():
    result = subprocess.run(
        ["gh", "issue", "close", str(number), "--comment", body],
        capture_output=True, text=True, encoding="utf-8"
    )
    print(f"#{number}: {result.returncode} {result.stdout.strip()}{result.stderr.strip()}")
