<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MangaFlow.Native</AssemblyName>
    <ApplicationIcon>../src-tauri/icons/icon.ico</ApplicationIcon>
    <Version>0.3.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>MangaFlow.Native.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
