"""initial core schema

Revision ID: 949d8856e6a4
Revises:
Create Date: 2026-07-14 20:17:23.459181
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "949d8856e6a4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "continuity_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scene_id", sa.String(length=36), nullable=True),
        sa.Column("panel_id", sa.String(length=36), nullable=True),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_continuity_snapshots_panel_id"), "continuity_snapshots", ["panel_id"], unique=False
    )
    op.create_index(
        op.f("ix_continuity_snapshots_scene_id"), "continuity_snapshots", ["scene_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("reading_direction", sa.String(length=8), nullable=False),
        sa.Column("page_ratio", sa.String(length=32), nullable=False),
        sa.Column(
            "default_resolution",
            sa.Enum("DRAFT_1K", "STANDARD_2K", "HIGH_4K", name="resolution"),
            nullable=False,
        ),
        sa.Column(
            "draft_resolution",
            sa.Enum("DRAFT_1K", "STANDARD_2K", "HIGH_4K", name="resolution"),
            nullable=False,
        ),
        sa.Column(
            "workflow_mode",
            sa.Enum("AUTO", "DIRECTOR", "SEMI_AUTO", name="workflowmode"),
            nullable=False,
        ),
        sa.Column("default_concurrency", sa.Integer(), nullable=False),
        sa.Column("ocr_enabled", sa.Boolean(), nullable=False),
        sa.Column("consistency_check_enabled", sa.Boolean(), nullable=False),
        sa.Column("default_style_id", sa.String(length=36), nullable=True),
        sa.Column("text_model_alias", sa.String(length=64), nullable=False),
        sa.Column("image_model_alias", sa.String(length=64), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "ANALYZED",
                "GENERATED",
                "NEEDS_CONFIRMATION",
                "CANONICAL",
                "ARCHIVED",
                name="assetstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "sha256"),
    )
    op.create_index(op.f("ix_assets_project_id"), "assets", ["project_id"], unique=False)
    op.create_table(
        "chapters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_source_revision_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "ordinal"),
    )
    op.create_index(op.f("ix_chapters_project_id"), "chapters", ["project_id"], unique=False)
    op.create_table(
        "characters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("canonical_description", sa.Text(), nullable=False),
        sa.Column("locked_features", sa.JSON(), nullable=False),
        sa.Column("forbidden_changes", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "ANALYZED",
                "GENERATED",
                "NEEDS_CONFIRMATION",
                "CANONICAL",
                "ARCHIVED",
                name="assetstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_characters_project_id"), "characters", ["project_id"], unique=False)
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("job_type", sa.String(length=48), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING",
                "QUEUED",
                "PREPARING",
                "UPLOADING_REFERENCES",
                "GENERATING",
                "OCR_CHECKING",
                "CONSISTENCY_CHECKING",
                "REPAIRING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                "NEEDS_REVIEW",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("model_alias", sa.String(length=64), nullable=True),
        sa.Column("request_parameters", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generation_jobs_project_id"), "generation_jobs", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_generation_jobs_status"), "generation_jobs", ["status"], unique=False)
    op.create_table(
        "style_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("color_mode", sa.String(length=24), nullable=False),
        sa.Column("profile", sa.JSON(), nullable=False),
        sa.Column("locked_fields", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ANALYZING", "DRAFT", "TEST_GENERATED", "CONFIRMED", "ACTIVE", name="stylestatus"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_style_profiles_project_id"), "style_profiles", ["project_id"], unique=False
    )
    op.create_table(
        "generation_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("location", sa.String(length=64), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("prompt_template", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("prompt_checksum", sa.String(length=64), nullable=False),
        sa.Column("input_versions", sa.JSON(), nullable=False),
        sa.Column("reference_asset_ids", sa.JSON(), nullable=False),
        sa.Column("provider_request_id", sa.String(length=200), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("output_asset_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["generation_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generation_records_job_id"), "generation_records", ["job_id"], unique=False
    )
    op.create_table(
        "job_dependencies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("depends_on_job_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["depends_on_job_id"], ["generation_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["generation_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "depends_on_job_id"),
    )
    op.create_index(
        op.f("ix_job_dependencies_job_id"), "job_dependencies", ["job_id"], unique=False
    )
    op.create_table(
        "manga_pages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=36), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("page_function", sa.String(length=32), nullable=False),
        sa.Column("panel_count", sa.Integer(), nullable=False),
        sa.Column("reading_direction", sa.String(length=8), nullable=False),
        sa.Column(
            "resolution",
            sa.Enum("DRAFT_1K", "STANDARD_2K", "HIGH_4K", name="resolution"),
            nullable=False,
        ),
        sa.Column("style_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "STORYBOARDED",
                "DRAFT_GENERATING",
                "DRAFT_READY",
                "REVIEW_REQUIRED",
                "APPROVED",
                "FINAL_GENERATING",
                "FINAL_CHECKING",
                "FINAL_READY",
                "EXPORTED",
                "FAILED",
                "NEEDS_REPAIR",
                "NEEDS_MANUAL_REVIEW",
                name="pagestatus",
            ),
            nullable=False,
        ),
        sa.Column("scene_ids", sa.JSON(), nullable=False),
        sa.Column("beat_ids", sa.JSON(), nullable=False),
        sa.Column("locked_fields", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chapter_id", "page_number", "version"),
    )
    op.create_index(op.f("ix_manga_pages_chapter_id"), "manga_pages", ["chapter_id"], unique=False)
    op.create_table(
        "outfits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("character_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("components", sa.JSON(), nullable=False),
        sa.Column("state_rules", sa.JSON(), nullable=False),
        sa.Column("locked_fields", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "ANALYZED",
                "GENERATED",
                "NEEDS_CONFIRMATION",
                "CANONICAL",
                "ARCHIVED",
                name="assetstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outfits_character_id"), "outfits", ["character_id"], unique=False)
    op.create_index(op.f("ix_outfits_project_id"), "outfits", ["project_id"], unique=False)
    op.create_table(
        "scenes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("time_label", sa.String(length=120), nullable=False),
        sa.Column("weather", sa.String(length=120), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("emotional_arc", sa.Text(), nullable=False),
        sa.Column("source_range", sa.JSON(), nullable=False),
        sa.Column("outfit_assignments", sa.JSON(), nullable=False),
        sa.Column("locked_fields", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scenes_chapter_id"), "scenes", ["chapter_id"], unique=False)
    op.create_table(
        "source_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chapter_id", "revision"),
    )
    op.create_index(
        op.f("ix_source_revisions_chapter_id"), "source_revisions", ["chapter_id"], unique=False
    )
    op.create_table(
        "beats",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scene_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("dialogue", sa.Text(), nullable=False),
        sa.Column("narration", sa.Text(), nullable=False),
        sa.Column("subtext", sa.Text(), nullable=False),
        sa.Column("emotion", sa.String(length=120), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("must_visualize", sa.Boolean(), nullable=False),
        sa.Column("mergeable", sa.Boolean(), nullable=False),
        sa.Column("page_turn_hook", sa.Boolean(), nullable=False),
        sa.Column("source_range", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_beats_scene_id"), "beats", ["scene_id"], unique=False)
    op.create_table(
        "inspection_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("generation_record_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=48), nullable=False),
        sa.Column("outcome", sa.String(length=48), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("regions", sa.JSON(), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_record_id"], ["generation_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inspection_results_generation_record_id"),
        "inspection_results",
        ["generation_record_id"],
        unique=False,
    )
    op.create_table(
        "panels",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("page_id", sa.String(length=36), nullable=False),
        sa.Column("reading_order", sa.Integer(), nullable=False),
        sa.Column("bounds", sa.JSON(), nullable=False),
        sa.Column("shot_type", sa.String(length=64), nullable=False),
        sa.Column("camera_angle", sa.String(length=64), nullable=False),
        sa.Column("camera_height", sa.String(length=64), nullable=False),
        sa.Column("characters", sa.JSON(), nullable=False),
        sa.Column("outfits", sa.JSON(), nullable=False),
        sa.Column("actions", sa.JSON(), nullable=False),
        sa.Column("expressions", sa.JSON(), nullable=False),
        sa.Column("background", sa.Text(), nullable=False),
        sa.Column("bubble_regions", sa.JSON(), nullable=False),
        sa.Column("sound_effects", sa.JSON(), nullable=False),
        sa.Column("bleed", sa.Boolean(), nullable=False),
        sa.Column("borderless", sa.Boolean(), nullable=False),
        sa.Column("locked_fields", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["page_id"], ["manga_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("page_id", "reading_order"),
    )
    op.create_index(op.f("ix_panels_page_id"), "panels", ["page_id"], unique=False)
    op.create_table(
        "dialogues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("panel_id", sa.String(length=36), nullable=False),
        sa.Column("speaker_character_id", sa.String(length=36), nullable=True),
        sa.Column("target_text", sa.Text(), nullable=False),
        sa.Column("reading_order", sa.Integer(), nullable=False),
        sa.Column("text_direction", sa.String(length=16), nullable=False),
        sa.Column("region", sa.JSON(), nullable=False),
        sa.Column("rewrite_forbidden", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["panel_id"], ["panels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("panel_id", "reading_order"),
    )
    op.create_index(op.f("ix_dialogues_panel_id"), "dialogues", ["panel_id"], unique=False)
    op.create_table(
        "repair_plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("inspection_result_id", sa.String(length=36), nullable=False),
        sa.Column("repair_type", sa.String(length=48), nullable=False),
        sa.Column("target_regions", sa.JSON(), nullable=False),
        sa.Column("target_fields", sa.JSON(), nullable=False),
        sa.Column("lock_conflicts", sa.JSON(), nullable=False),
        sa.Column("automatic_attempts", sa.Integer(), nullable=False),
        sa.Column("max_automatic_attempts", sa.Integer(), nullable=False),
        sa.Column("manual_review_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inspection_result_id"], ["inspection_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repair_plans_inspection_result_id"),
        "repair_plans",
        ["inspection_result_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repair_plans_inspection_result_id"), table_name="repair_plans")
    op.drop_table("repair_plans")
    op.drop_index(op.f("ix_dialogues_panel_id"), table_name="dialogues")
    op.drop_table("dialogues")
    op.drop_index(op.f("ix_panels_page_id"), table_name="panels")
    op.drop_table("panels")
    op.drop_index(
        op.f("ix_inspection_results_generation_record_id"), table_name="inspection_results"
    )
    op.drop_table("inspection_results")
    op.drop_index(op.f("ix_beats_scene_id"), table_name="beats")
    op.drop_table("beats")
    op.drop_index(op.f("ix_source_revisions_chapter_id"), table_name="source_revisions")
    op.drop_table("source_revisions")
    op.drop_index(op.f("ix_scenes_chapter_id"), table_name="scenes")
    op.drop_table("scenes")
    op.drop_index(op.f("ix_outfits_project_id"), table_name="outfits")
    op.drop_index(op.f("ix_outfits_character_id"), table_name="outfits")
    op.drop_table("outfits")
    op.drop_index(op.f("ix_manga_pages_chapter_id"), table_name="manga_pages")
    op.drop_table("manga_pages")
    op.drop_index(op.f("ix_job_dependencies_job_id"), table_name="job_dependencies")
    op.drop_table("job_dependencies")
    op.drop_index(op.f("ix_generation_records_job_id"), table_name="generation_records")
    op.drop_table("generation_records")
    op.drop_index(op.f("ix_style_profiles_project_id"), table_name="style_profiles")
    op.drop_table("style_profiles")
    op.drop_index(op.f("ix_generation_jobs_status"), table_name="generation_jobs")
    op.drop_index(op.f("ix_generation_jobs_project_id"), table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_index(op.f("ix_characters_project_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_chapters_project_id"), table_name="chapters")
    op.drop_table("chapters")
    op.drop_index(op.f("ix_assets_project_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_continuity_snapshots_scene_id"), table_name="continuity_snapshots")
    op.drop_index(op.f("ix_continuity_snapshots_panel_id"), table_name="continuity_snapshots")
    op.drop_table("continuity_snapshots")
    # ### end Alembic commands ###
