// Chinese UI copy for the visual storyboard canvas (V02-31B audit §6).
export const storyboardCopy = {
  canvasLabel: "页画布",
  loading: "正在读取本页分镜",
  loadError: "本页分镜读取失败",
  retry: "重试",
  noPanels: "本页没有格子。从剧本重新计算，或等待后续版本允许手工建格。",
  zoomIn: "放大",
  zoomOut: "缩小",
  fit: "适配窗口",
  reset: "复位",
  snap: "吸附",
  readingOrder: "阅读序",
  bleedFrame: "出血框",
  safeArea: "安全区",
  undo: "撤销",
  redo: "重做",
  savePage: "保存本页",
  saving: "保存中",
  focusMode: "专注模式",
  exitFocusMode: "退出专注",
  inspectorToggle: "属性面板",
  layerList: "图层",
  layerPage: "本页",
  layerBubbleSuffix: "气泡",
  geometryReadoutTitle: "几何（只读）",
  polygonNote: "此格为多边形，画布暂不支持拖拽与缩放；矩形调整手柄已禁用。",
  canvasMissing: "本页缺少画布尺寸字段，出血框与安全区暂不可用。",
  bubbleBelongs: "气泡仍属于本格",
  conflict: "分镜格已在别处更新，画布草稿已保留",
  discardReload: "放弃草稿并重新加载",
  leaveConfirm: "分镜画布有未保存的几何草稿，离开将丢失。确定离开吗？",
  pageMenu: "页菜单",
  rebuildLayout: "重建本页版式…",
  rebuildTitle: "重建本页版式",
  rebuildWarning: "重建将删除本页全部格子与气泡，并从已确认剧本与原文区间重新映射；已生成候选会因分镜版本过期。这不是视觉拖拽的替代操作。",
  rebuildCount: "本页格数",
  rebuildMode: "版式",
  layoutDynamic: "动态错落",
  layoutBalanced: "均衡网格",
  rebuildConfirm: "确认重建",
  rebuildCancel: "取消",
  rebuildNotice: "版式已重建，画布草稿已清空。",
  savedNotice: (version: number, candidates: number) => `已保存 · 当前 V${version} · 将使 ${candidates} 个候选过期`,
  selectedAnnouncement: (readingOrder: number, bleed: boolean) =>
    `已选中第 ${readingOrder} 格${bleed ? "，出血格" : ""}`,
  bubbleSelectedAnnouncement: (readingOrder: number) => `已选中阅读序 ${readingOrder} 的气泡`,
  handleResize: (corner: string) => `调整${corner}`,
  tailHandle: "调整尾巴终点",
  anchorHandle: "调整气泡锚点",
} as const;

export const handleCornerLabels: Record<string, string> = {
  nw: "左上角",
  n: "上边",
  ne: "右上角",
  e: "右边",
  se: "右下角",
  s: "下边",
  sw: "左下角",
  w: "左边",
};
